twig:
    default_path: '%kernel.project_dir%/templates'
    paths: 
        '%kernel.project_dir%/templates/app/private/layout': layout
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
