version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '8741:80'
    volumes:
      - ${PROJECT_ROOT}:/var/www/CertificadosMedUNLP
      - './apache2:/etc/apache2/sites-enabled'
    depends_on:
      - database
  phpmyadmin:
    depends_on:
      - database
    links:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: database
      MYSQL_USERNAME: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}" 
    networks:
      - backend
    volumes:
      - /sessions
    container_name: phpmyadmin
networks:
  backend: